In [18]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import yfinance as yf
import talib as ta

In [35]:
plt.style.use('seaborn')
stocks = ['A2M', 'BHP', 'CBA', 'NAB', 'WES', 'MQG']
asx=['A2M','AAA','ABC','ABP','AFI','AGL','AIA','ALD','ALL','ALQ','ALU','ALX','AMC','AMP','ANN','ANZ','APA','APE','APT','APX','ARB','ARG','AST','ASX','AWC','AZJ','BAP','BEN','BGA','BHP','BIN','BKW','BLD','BOQ','BPT','BRG','BSL','BWP','BXB','CAR','CBA','CCL','CCP','CDA','CGF','CHC','CHN','CIA','CIM','CLW','CMW','CNU','COH','COL','CPU','CQR','CSL','CSR','CTD','CWN','CWY','DEG','DHG','DMP','DOW','DRR','DXS','EBO','ELD','EML','EVN','EVT','FBU','FLT','FMG','FPH','GMG','GNE','GOZ','GPT','GXY','HLS','HVN','IAG','IEL','IFL','IFT','IGO','ILU','IOO','IOZ','IPL','IRE','IVV','JBH','JHX','LFG','LFS','LLC','LNK','LYC','MCY','MEZ','MFG','MGF','MGOC','MGR','MIN','MLT','MP1','MPL','MQG','MTS','NAB','NCM','NEC','NHF','NIC','NSR','NST','NUF','NWL','NXT','ORA','ORE','ORG','ORI','OSH','OZL','PBH','PDL','PLS','PME','PMGOLD','PMV','PNI','PNV','PPT','PTM','QAN','QBE','QUB','REA','REH','RHC','RIO','RMD','RRL','RWC','S32','SCG','SCP','SDF','SEK','SGM','SGP','SGR','SHL','SKC','SKI','SLK','SNZ','SOL','SPK','STO','STW','SUL','SUN','SVW','SYD','TAH','TCL','TLS','TLT','TNE','TPG','TWE','TYR','VAP','VAS','VCX','VEA','VEU','VGS','VOC','VTS','VUK','WAM','WBC','WEB','WES','WOR','WOW','WPL','WPR','WTC','XRO','YAL','Z1P','ZIM']
for stock in stocks:
    stock_info = yf.Ticker(f'{stock}.AX')
    df_stock = stock_info.history(period="5y")
    try:
        df_stock.columns = [f'Open_{stock}', 
                                          f'High_{stock}',
                                          f'Low_{stock}',
                                          f'Close_{stock}',
                                          f'Volume_{stock}',
                                          f'Dividends_{stock}',
                                          f'Stock Splits_{stock}']   
        
        df_stock[f'EMA_{stock}'] = ta.EMA(df_stock[f'Close_{stock}'],timeperiod=5)
        df_stock[f'UpperBand_{stock}'],df_stock[f'MiddleBand_{stock}'],df_stock[f'LowerBand_{stock}'] = ta.BBANDS(df_stock[f'Close_{stock}'], timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)
        df_stock[f'OBV_{stock}'] = ta.OBV(df_stock[f'Close_{stock}'], df_stock[f'Volume_{stock}'])
        if asx.index(stock) == 0:
            df = df_stock
        df = merge=pd.merge(df,df_stock, how='inner', left_index=True, right_index=True)
    except:
        print(f'could not split columns for {stock}')

df.to_csv('Historical_data_asx.csv')

In [36]:
df

,Open_A2M_x,High_A2M_x,Low_A2M_x,Close_A2M_x,Volume_A2M_x,Dividends_A2M_x,Stock Splits_A2M_x,EMA_A2M_x,UpperBand_A2M_x,MiddleBand_A2M_x,...,Low_MQG,Close_MQG,Volume_MQG,Dividends_MQG,Stock Splits_MQG,EMA_MQG,UpperBand_MQG,MiddleBand_MQG,LowerBand_MQG,OBV_MQG
Date,,,,,,,,,,,,,,,,,,,,,
2017-11-28 00:00:00+11:00,7.74,7.770,7.490,7.63,5486459,0,0,NaN,NaN,NaN,...,81.981459,82.063934,1183461,0.0,0,NaN,NaN,NaN,NaN,1183461.0
2017-11-29 00:00:00+11:00,7.65,7.670,7.520,7.58,3626179,0,0,NaN,NaN,NaN,...,82.080430,82.286621,922407,0.0,0,NaN,NaN,NaN,NaN,2105868.0
2017-11-30 00:00:00+11:00,7.54,7.620,7.450,7.59,4006842,0,0,NaN,NaN,NaN,...,81.016502,81.016502,2246658,0.0,0,NaN,NaN,NaN,NaN,-140790.0
2017-12-01 00:00:00+11:00,7.60,7.630,7.490,7.51,2270816,0,0,NaN,NaN,NaN,...,80.917512,80.991737,901581,0.0,0,NaN,NaN,NaN,NaN,-1042371.0
2017-12-04 00:00:00+11:00,7.47,7.510,7.320,7.48,3350093,0,0,7.558000,7.667836,7.558,...,80.018536,80.373184,1106275,0.0,0,81.346396,82.783236,81.346396,79.909555,-2148646.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-11-22 00:00:00+11:00,6.05,6.190,6.040,6.18,2643289,0,0,6.052599,6.238789,6.066,...,175.830002,176.000000,692472,0.0,0,177.353370,180.844978,178.132001,175.419023,83323078.0
2022-11-23 00:00:00+11:00,6.18,6.250,6.180,6.21,2130918,0,0,6.105066,6.299742,6.106,...,177.029999,178.720001,567780,0.0,0,177.808914,181.027438,178.286002,175.544565,83890858.0
2022-11-24 00:00:00+11:00,6.22,6.255,6.105,6.11,1466458,0,0,6.106711,6.287061,6.098,...,177.250000,177.990005,519425,0.0,0,177.869278,180.184437,177.918002,175.651568,83371433.0
2022-11-25 00:00:00+11:00,6.14,6.270,6.140,6.24,2037375,0,0,6.151140,6.300554,6.156,...,177.475006,177.949997,445490,0.0,0,177.896184,179.450859,177.644000,175.837141,82925943.0
2022-11-28 00:00:00+11:00,6.22,6.240,6.140,6.16,879226,0,0,6.154094,6.268544,6.180,...,176.529999,178.300003,153005,0.0,0,178.030790,179.667034,177.792001,175.916968,83078948.0

In [21]:
df_stock

,Open_MQG,High_MQG,Low_MQG,Close_MQG,Volume_MQG,Dividends_MQG,Stock Splits_MQG,MA
Date,,,,,,,,
2017-11-28 00:00:00+11:00,83.160871,83.354691,81.981459,82.063934,1183461,0.0,0,NaN
2017-11-29 00:00:00+11:00,83.127883,83.400056,82.080430,82.286621,922407,0.0,0,NaN
2017-11-30 00:00:00+11:00,82.022716,82.138182,81.016510,81.016510,2246658,0.0,0,NaN
2017-12-01 00:00:00+11:00,81.486608,81.696920,80.917519,80.991745,901581,0.0,0,NaN
2017-12-04 00:00:00+11:00,80.859798,81.074238,80.018536,80.373184,1106275,0.0,0,81.346399
...,...,...,...,...,...,...,...,...
2022-11-22 00:00:00+11:00,177.389999,177.460007,175.830002,176.000000,692472,0.0,0,178.132001
2022-11-23 00:00:00+11:00,177.369995,179.339996,177.029999,178.720001,567780,0.0,0,178.286002
2022-11-24 00:00:00+11:00,178.610001,179.389999,177.250000,177.990005,519425,0.0,0,177.918002
2022-11-25 00:00:00+11:00,177.690002,178.710007,177.475006,177.949997,445490,0.0,0,177.644000
2022-11-28 00:00:00+11:00,177.429993,178.360001,176.529999,178.119995,145247,0.0,0,177.756000